### ISSUE TITLE
Incompatible AWS Version

### ISSUE THREAD

**Issue by ramirocastillo93** [angadsingh/s3sync#1]
Hi! I'm trying to use this package but when trying the command `sudo python3 s3sync.py --config config.yaml init` it shows the message `Error: Found incompatible AWS CLI version [2.0.62]`. Removed that version and installed the AWS CLI 2.0.0 and the same error is showing.

Same happening with `s3sync --config ./config.yaml init`
`Error: Found incompatible AWS CLI version [2.0.0]`

AWS Version
`aws --version`
`aws-cli/2.0.0 Python/3.7.3 Linux/5.4.0-52-generic botocore/2.0.0dev4`

Ubuntu 20.04

**Comment by angadsingh** [comment]
Thanks you just reported a minor bug. I just fixed it and push an updated version (https://pypi.org/project/pys3sync/0.1.2/). Please try now. What was happening was that due to a naive string comparison, your version [2.0.62] was < [2.0.9] because I was doing just a string comparison. now using python package version comparison.

**Comment by angadsingh** [comment]
Also please go back to 2.0.62. it won't work with 2.0.0. needs atleast 2.0.9
